### ISSUE TITLE
Symfony 7 update

### ISSUE THREAD

**Issue by madmortigan1** [leapt/froala-editor-bundle#19]
Hello,

Is there a plan to update and support Symfony 7 ?

Thank you

**Comment by jmsche** [comment]
Hi, sorry for the delay, I'll add it probably this week :)

**Comment by jmsche** [comment]
Hi @madmortigan1,

v1.5.0 has just been released, with Symfony 7 support :) 

See https://github.com/leapt/froala-editor-bundle/releases/tag/v1.5.0

Cheers!

**Comment by madmortigan1** [comment]
Thank you for your support.
Have a great year
